### PR TITLE
Custom icons for different types of notifications.

### PR DESCRIPTION
**Pull request by florian-obernberger**
This PR adds unique icons to the different notification types. In particular the following types got custom icons:

- Favorites
- Reblogs / Boosts
- Mentions / Comments
- Follows
- Poll

Below you can see examples of all of them except the polls.

<table>
  <tr>
    <td width="25%">Favorite icon in status bar</td width="25%">
    <td width="25%">Mention icon in status bar</td width="25%">
    <td width="25%">Reblog icon in status bar</td width="25%">
    <td width="25%">Follow icon in status bar</td width="25%">
  </tr>
  <tr>
    <td width="25%"><p>Favorite icon in status bar</p></td width="25%">
    <td width="25%"><p>Mention icon in status bar</p></td width="25%">
    <td width="25%"><p>Reblog icon in status bar</p></td width="25%">
    <td width="25%"><p>Follow icon in status bar</p></td width="25%">
  </tr>
</table>

<table>
  <tr>
    <td width="25%">Favorite icon in notification pll down</td width="25%">
    <td width="25%">Mention icon in notification pll down</td width="25%">
    <td width="25%">Reblog icon in notification pll down</td width="25%">
    <td width="25%">Follow icon in notification pll down</td width="25%">
  </tr>
  <tr>
    <td width="25%"><p>Favorite icon in notification pll down</p></td width="25%">
    <td width="25%"><p>Mention icon in notification pll down</p></td width="25%">
    <td width="25%"><p>Reblog icon in notification pll down</p></td width="25%">
    <td width="25%"><p>Follow icon in notification pll down</p></td width="25%">
  </tr>
</table>

### CODE REVIEW

**Comment by sk22** [comment]
many thanks!!

**Comment by florian-obernberger** [comment]
you're very welcome! i hope the implementation was okay, even tho I'm not really a java dev!

I was also thinking about adding an option in the settings to enable / disable it, but my knowledge of the codebase and java is not (yet?) good enough to do that.

**Comment by sk22** [comment]
oh me neither… i mean i did do a lot of java back in school, but never really lots of android. this project just kinda forced me back into it - like, it just started by adding back the federated timeline, which was simple enough 😅
tbh, i don't think a setting option for this will be really necessary, so all good!

**Comment by sk22** [comment]
also, thanks for discovering that fluent icons do actually include an @ icon - for some reason, upstream uses fluent icons for virtually anything except the @ symbol

**Comment by florian-obernberger** [comment]
> oh me neither… i mean i did ...

That's nice tho!! I am more of a Flutter dev, but I'll have to get used to Android native anyways because some things just can't be done in Flutter (Notifications for example).

> also, thanks for discovering that fluent icons do actually include an @ icon - for some reason, upstream uses fluent icons for virtually anything except the @ symbol

Yep haha. Since I already added the icon to the drawables it should be an easy switch now. There's also already a [PR (#467)](https://github.com/mastodon/mastodon-android/pull/476) upstream, that does exactly that, you could probably also just merge that.

**Pull request merged**
