### PR TITLE
Proper implementation of the color picker

### LINKED ISSUE #90: The ability to choose your own accent color
It would be nice to add the ability for users to choose a color scheme for the application. For starters, you could make options such as blue (the original color), purple (the official service color), pink (the color of the app), and a monochrome theme

### PR DESCRIPTION
**Pull request by LucasGGamerM**
This time, following the recommendations of @sk22, I can finally say I fixed #90 with a golden key. Its now a menu instead of a switch, and its also quite simple to add new themes. I myself plan on making a green theme later :D

### CODE REVIEW

**Comment by LucasGGamerM** [comment]
This is a preview of what it looks like right now 

https://user-images.githubusercontent.com/71328265/205315567-48a9c2b3-d057-4ade-808b-f37da3b066e5.mp4

**Comment by LucasGGamerM** [comment]
And now there is a green theme

**Comment by LucasGGamerM** [comment]
I have made the green theme a little better. A lot better in fact. I extracted the colors from the green material you pallet on my phone, and i am quite pleased with the results :D

**Comment by LucasGGamerM** [comment]
Screenshot_20221203-134713
Screenshot_20221203-134708
Look at them! They are quite gorgeous imo

**Comment by LucasGGamerM** [comment]
Working on a blue theme right now :D

**Comment by LucasGGamerM** [comment]
Doing some refactoring

**Comment by muznyo** [comment]
have you thought about dynamic colors option?

**Comment by LucasGGamerM** [comment]
This project has some conflicting classes if I import the required libraries for dynamic colors, which means that I cant compile it right if I use the libraries responsible for dynamic colors.

**Comment by LucasGGamerM** [comment]
Screenshot_20221203-222951
And now there is a beautiful little icon there :D

**Comment by LucasGGamerM** [comment]
On testing I found some readability problems with the light blue theme, will look into it

**Comment by LucasGGamerM** [comment]
Now working on an orange and yellow theme

**Comment by LucasGGamerM** [comment]
image
Oh boy the orange the is FIRE

**Comment by LucasGGamerM** [comment]
image
Oh boy, the orange theme is FIRE

**Comment by LucasGGamerM** [comment]
Time to work on a yellow theme :D

**Comment by LucasGGamerM** [comment]
image
image
Now there is a beautiful yellow theme!

**Comment by LucasGGamerM** [comment]
And now I shall work on getting the TrueBlack theme just right and also get the fab and post buttons to follow the color scheme

**Comment by LucasGGamerM** [comment]
So all i need to do to finish this is to make it so that the publish button also follows the theme. Because as it is, its quite not great

**Comment by LucasGGamerM** [comment]
So, I would say that its basically done. If you find any inconsistencies with the theme picker please share

**Comment by LucasGGamerM** [comment]
So yes, it's done. There is hardly anything that catches the eye as incoherent anymore. Hopefully this gets merged

**Comment by sk22** [comment]
the themes look really good, thanks a lot for all your efforts!!

**Comment by LucasGGamerM** [comment]
Lovely, I ended up creating my own fork of megalodon called moshidon. In case I make any other meaningful changes I will also try to pull request them here :D

**Pull request merged**
