### PR TITLE
feat(composeButton): hide fab on scroll

### PR DESCRIPTION
**Pull request by FineFindus**
Adds an animation, that hides the Compose Imagebutton when scrolling down. This change provides more visible screen space for posts when scrolling down, since the button was obscuring a relatively large portion of the screen, especially on phones with smaller screen sizes.
The animation only applies in the Timelines tab, and won't work on profiles, which is why I'm opening this as a draft for now.

https://user-images.githubusercontent.com/63370021/213286445-bcb73213-eb54-4dab-b759-83d4875a08a1.mp4

### CODE REVIEW

**Comment by FineFindus** [comment]
Added the hiding animation on the profile page as well, enabled in all tabs, except the about tab. There is also an issue with the button not hiding when scrolling down, if only a few (usually a single one) posts are shown, as can be seen in the video below in the media tab. 
I don't consider that a bug, and won't fix it, since there is no need to hide the compose button, in these cases, there is already enough free space.


https://user-images.githubusercontent.com/63370021/213534283-2c3f0d50-6844-4e30-b383-65518fbf1d7a.mp4

**Comment by LucasGGamerM** [comment]
I am gonna steal this one

**Comment by sk22** [comment]
appears to be a bit buggy in the profile section: setting `isScrolling` to true by default fixes the FABs popping up when the tabs load, but scrolling the profile info doesn't affect the FAB at all (which is bad because if it's hidden, users can't easily get the FAB to show up again). i've tried to fix it for a while now (by also listening to ProfileFragment's scroll events), but i can't get it to work right now :/

**Comment by sk22** [comment]
(also, i can't push anything to the PR)

**Comment by LucasGGamerM** [comment]
I think I have fixed this bug in Moshidon, you can take a look there

**Comment by LucasGGamerM** [comment]
Found it, this is the relevant commit for fixing the issue you saw 870ac2b946884fa16c8b1d17f8002755747926bb

**Comment by sk22** [comment]
uhm, no, this didn't fix what i meant :/

**Comment by FineFindus** [comment]
> (also, i can't push anything to the PR)

Fixed, I accidentally clicked the wrong button.

> by also listening to ProfileFragment's scroll events

That was my original idea, but it doesn't work, which is why I only implemented the current version.


> Found it, this is the relevant commit for fixing the issue you saw https://github.com/sk22/megalodon/commit/870ac2b946884fa16c8b1d17f8002755747926bb

I think it actually introduced bugged behavior, it does not hide when scrolling down the first time.

**Comment by LucasGGamerM** [comment]
I need to look on the fab situation soon

**Comment by LucasGGamerM** [comment]
> appears to be a bit buggy in the profile section: setting `isScrolling` to true by default fixes the FABs popping up when the tabs load, but scrolling the profile info doesn't affect the FAB at all (which is bad because if it's hidden, users can't easily get the FAB to show up again). i've tried to fix it for a while now (by also listening to ProfileFragment's scroll events), but i can't get it to work right now :/

I just fixed this specific bug on 211e6cdee28047b6fb24519169a28fb9b7e69a23

**Comment by FineFindus** [comment]
> > appears to be a bit buggy in the profile section: setting `isScrolling` to true by default fixes the FABs popping up when the tabs load, but scrolling the profile info doesn't affect the FAB at all (which is bad because if it's hidden, users can't easily get the FAB to show up again). i've tried to fix it for a while now (by also listening to ProfileFragment's scroll events), but i can't get it to work right now :/
> 
> I just fixed this specific bug on 211e6cdee28047b6fb24519169a28fb9b7e69a23

Yes, but that also removes the hiding behavior entirely on the profile fragment.

I'm currently investigating a new solution,which hopefully fixes it.

**Comment by LucasGGamerM** [comment]
This is a weird problem

**Comment by FineFindus** [comment]
I reworked the implementation, the button now only shows after scrolling up a small distance (the value might have to be changed, it's set to `400` for now). The users now has to actually scroll up, and not just accidentally move up a few pixels (this should also fix bugs like https://github.com/LucasGGamerM/moshidon/issues/51).

With the new implementation, the FAB does no longer pop up when switching tabs in the profile section.
 
https://user-images.githubusercontent.com/63370021/214901780-0fd652a7-b444-4ffc-93f0-4dc343be63e7.mp4


I've found the following two issues, which still remain with this pr, 
- Scrolling in the profile about tab/ the info does not have any effect on the FAB
- FAB state is not saved across timelines, so each timeline has its own fab state 

Not sure how to solve them yet, but I'll continue to work on them.

**Comment by LucasGGamerM** [comment]
That is quite the discussion right there

**Comment by FineFindus** [comment]
Found a working solution, the fab now works in all profile tabs. I think this should to ready for review now.

[FAB in Profile](https://user-images.githubusercontent.com/63370021/215354297-ef9253d2-ae3f-48ea-a25c-4e26b9abf15d.webm)

**Comment by FineFindus** [comment]
> This has been a thing on moshidon since release 88, and it's completely fine here

It's not. Fab on the profile page will only be hidden when scrolling inside the tabs, that contain posts, not in the profile itself, like the header or the about tab. [e7e3d94](https://github.com/sk22/megalodon/pull/327/commits/e7e3d94add2e30a3e2fa5e51c2a782c87c9f6497) implements exactly that, as can be somewhat seen from the video.

**Comment by fuzzmz** [comment]
Looking at the implementations, and what Moshidon is also doing, hiding the fab doesn't really do much when catching up with new posts. Say for example you have 20 new posts since you last opened the app, this means scrolling up which in turn makes the compose button pop up.

Any ideas on how to address this? All the things I'm thinking about, such as a timer between the scroll (regardless of direction) stops and when the button appears, don't feel like the best solution.

**Comment by FineFindus** [comment]
I personally feel like this is not really an issue. When scrolling down, the fab obscures part of the incoming posts, whereas when scrolling up, post move in from the top, so the fab is not really in the way and can more easily be ignored. Also, you can just start at the top and the catch-up scrolling down.

> such as a timer between the scroll (regardless of direction) stops and when the button appears, don't feel like the best solution.

I think a similar implementation, but instead of the timer, I would use the scroll distance, similar to how it's already used to hide the fab for a certain distance when scrolling up. I think the current implementation could be modified to accommodate these changes if wanted.

Also, @sk22, the pull request has some merge issues, I would resolve them after you reviewed it.

**Comment by LucasGGamerM** [comment]
I have made a bunch of small improvements to the implementation from @FineFindus, primarily by fixing this issue on the moshidon github https://github.com/LucasGGamerM/moshidon/issues/88

**Comment by FineFindus** [comment]
Based on the suggestion from @LucasGGamerM, I implemented the feature, that is fab will always be visible, if the user is scrolled to the top of a page. This is works in both the timelines and the profile page.

**Comment by FineFindus** [comment]
Can you check if you are using the latest commits? I believe this was an issue with the first draft, and has been fixed now, as I cannot reproduce it.


https://user-images.githubusercontent.com/63370021/218545564-5237518b-e848-48e9-b877-ce5d402bbf12.mp4

**Comment by sk22** [comment]
> Can you check if you are using the latest commits? I believe this was an issue with the first draft, and has been fixed now, as I cannot reproduce it.

my bad, i thought the VS Code GitHub extension would pull automatically when i switch to a PR...

anyway, merged this via #435 as i couldn't push to this PR

**Pull request closed without merging**
