### PR TITLE
fix: show multiline poll options

### PR DESCRIPTION
**Pull request by FineFindus**
Fixes an issue, where long poll options were not shown completely and instead truncated.

| Before                                                                                                              	| After                                                                                                                                      	|
|---------------------------------------------------------------------------------------------------------------------	|--------------------------------------------------------------------------------------------------------------------------------------------	|
| Poll with truncated line 	| Poll with mutliline|

### CODE REVIEW

**Comment by FineFindus** [comment]
I think this requires a bit more work

**Comment by sk22** [comment]
huhh?? it works on my end...
Screenshot_20231001-010847_Megalodon
Screenshot_20231001-010857_Megalodon

**Comment by sk22** [comment]
i don't understand why your system wouldn't wrap the text / display more than one line, and even more do i not understand why the minHeight of 48dp doesn't get applied.. if you have time, could you try experimenting with it and try to find out how to fix it? (since i don't seem to have that issue myself)

**Comment by FineFindus** [comment]
Ok, I checked and this is only an issue in Moshidon, sorry.

**Comment by sk22** [comment]
oh! huh

**Pull request merged**
