### PR TITLE
feat: hastag timelines with multiple tags

### PR DESCRIPTION
**Pull request by FineFindus**
Brings over a feature from the web client, which allows viewing multiple hashtags at once or blocking certain ones from a timeline.

Example of a web timeline:
Web feature

The user can edit which hashtags are (not) loaded in the timelines edit screen by clicking on a hashtag timeline. The additional text fields are only displayed if the timeline is a hashtag timeline.
In app edit hashtag timeline

### CODE REVIEW

**Comment by LucasGGamerM** [comment]
I might rewrite this using a better UI. Because on the web interface it looks like you can search hashtags on typing it, and you can also enable "local only" posts, which is useful. Also hiding the huge amount of options inside an "Advanced" dropdown menu would put less strain on the users

**Comment by sk22** [comment]
omg i didn't even know the mastodon api natively supports the "any", "all" and "none" parameters for hashtag timelines (i thought each hashtag timeline would've needed to be fetched individually and the results be painfully combined) - now this definitely changes things

**Comment by FineFindus** [comment]
> i'm now looking into ways to improve the edit dialog, as @LucasGGamerM suggested. thanks a lot for this PR already!

Great, I'm aware that the UI is not the best, and I'm glad you're improving it as I dislike (translated: I hate it) Androids XML UI.

As for potential improvements, I played around with a chip edit text, this would more clearly indicate the hashtags, but it was not ideal, so I left it out.

Edittext with chips

**Comment by sk22** [comment]
okay so; i haven't gotten to the ui part yet because i really wanted to have a "add hashtag" button accessible directly from the "edit timelines" fragment. thing is, the timeline definitions were originally meant to be final (like, users weren't meant to be able to change which list a list timeline represents, or which hashtag it displays), so it only provided methods for changing the icon and display title. now since the hashtag timeline definitions can contain more data, this requires some refactoring - especially since i want the dialog to be able to also be able to create new timeline definitions for hashtags, not only edit existing ones.

**Comment by sk22** [comment]
(btw, i'm pretty sure i don't have write permissions on this PR since it lives on your fork of moshidon. i could push my changes to another branch tho)

**Comment by FineFindus** [comment]
Hmm, this definitely shouldn't be the case, especially, it shouldn't deny you to read it since it's public? I've invited you as a collaborator as a temporary fix, let's see if it works now.

**Comment by sk22** [comment]
yep, works. thanks!

**Pull request merged**
