### PR TITLE
Adding mastodon original colors toggle. Partially fixing #90

### PR DESCRIPTION
**Pull request by LucasGGamerM**
This commit is adding the mastodon original color toggle. Partially addressing #90. The implementation is quite clean, and i feel confident i can add more color options in the future. For now though, the pinkish and purplish colors are the only options.

### CODE REVIEW

**Comment by LucasGGamerM** [comment]
Done. Now its completely bugfree.

**Comment by LucasGGamerM** [comment]
I will do some more testing of this. Just in case i forgot something. For now though, I haven´t found any other bugs, and the feature should be working as expected.

**Comment by LucasGGamerM** [comment]
Yup, I am now confident its working alright, It should fine for release now :D

**Comment by sk22** [comment]
so, uhm, i don't really want to have a switch in the app that just applies the upstream color scheme. i changed it intentionally and it's part of the app's identity, so i don't really see a reason to include a “switch to official color scheme” feature. the pink theme is fine (and pretty).

again - i'd welcome a dropdown list of color schemes to enable for some customization; but i wouldn't know how to cleanly implement this without duplicating all the styles a bunch of times. for what this pull request is right now, i think it's fine to have them duplicated once, but i think it'd be cleaner to just have separate colors.xml files for each color scheme, but i don't know how that works. (i'm only an accidental, amateur android dev myself)

since you created a seperate pull request for this (i think?), i'll close this one

**Pull request closed without merging**
