### PR TITLE
feat(theme): add Nord theme

### PR DESCRIPTION
**Pull request by FineFindus**
This pr adds a [Nord theme option](https://nordtheme.com). 

<details>
<summary>Light</summary>

Post
Poll
Profile
Profile About
Settings

</details>

<details>
<summary>Dark</summary>

Post
Poll
Profile
Profile About
Settings

</details>

### CODE REVIEW

**Comment by FineFindus** [comment]
Hey, before I rebase this to be up to date with `main`, is this even something that you are interested in merging?

**Comment by LucasGGamerM** [comment]
I believe this need a rework. The contrast is too low on some navigation buttons. I will work on making it better though

**Comment by FineFindus** [comment]
I'm not a designer, so yes that is quite possible. If you could point me to some of the issues you found, I would try to fix them as well, since this needs to be rebase on `main` anyways.

**Comment by LucasGGamerM** [comment]
For some reason the app is beautifully crashing whenever I try to set my (rewritten) Nord theme

**Comment by FineFindus** [comment]
What is the stacktrace? I had an issue with a similar effect, so I just set the theme manually, for testing

**Comment by LucasGGamerM** [comment]
Got it working here. The theme still needs some tweaking though. You can find the code at https://github.com/LucasGGamerM/moshidon/tree/development_of_the_nord_theme

**Comment by LucasGGamerM** [comment]
Screenshot_20221222-192633
Screenshot_20221222-192613
Screenshot_20221222-192544
Some screenshots here

**Comment by LucasGGamerM** [comment]
I am going to rewrite the theme (again) but instead using the colors from my linux desktop with the nord theme applied.

**Comment by LucasGGamerM** [comment]
image
image
Here are some screenshots! Theses ones follow the nord theme a whole lot better!

**Comment by FineFindus** [comment]
Here's some quick feedback from me, after 5 Minutes of using it. It looks great, I just found a few minor things to nitpick.
Settings
The switches should have a higher contrast color, there currently very hard to distinguish from the background, maybe `nord8` would be better?

Same contrast issues is with polls and links in posts.
Polls contrast
Link contrast

These two UI elements are currently not correctly colored.
Popup color
Bar color

If I want to further improve the theme, should we continue discussing it in this pr? Or should I rather create a new one on your repo?

**Comment by LucasGGamerM** [comment]
It's indeed something I need to look into. But that's for tomorrow

**Comment by FineFindus** [comment]
Closing this, since it has been implemented in Moshidon. So it would be better to pull it from there.

**Pull request closed without merging**
