### PR TITLE
feat(search): show suicide help dialog

### PR DESCRIPTION
**Pull request by FineFindus**
If searching for the term `Suicide`, the following dialog will be shown.
Suicide help dialog

The user has the option of not showing this dialog on subsequent searches, by clicking "Don't show again".

A potential point of improvement may be to display an actual number of the local suicide hotline.

This feature was inspired by a similar screen in [Infinity for Reddit](https://github.com/Docile-Alligator/Infinity-For-Reddit/)

### CODE REVIEW

**Comment by sk22** [comment]
cw discussing ideas about suicide prevention

i don't know if a heart in a popup would be of any help to anyone in distress in this context; i can imagine that people might kinda feel mocked by it (but i'm not sure about that). other than that, i'm happy to merge this - thank you!

**Comment by FineFindus** [comment]
For that reason, I also included the mentioned of local help hotlines. I would hope nobody would feel mocked by it, as that totally wasn't my intention.

**Comment by sk22** [comment]
> For that reason, I also included the mentioned of local help hotlines. I would hope nobody would feel mocked by it, as that totally wasn't my intention.

i didn't think that would be your intention, obviously - i'm just not sure if the heart would be productive to show to someone who might be thinking about suicide. i mean, a heart is a symbol of love, and i could imagine someone might feel mocked, or maybe rather misunderstood, by an automated popup with just a symbol of love or compassion in the title - as if an app could provide that. maybe that makes sense?

**Comment by Murazaki** [comment]
If you want a call to action, maybe use this link : http://www.suicide.org/international-suicide-hotlines.html

**Comment by FineFindus** [comment]
I was looking for something like this. Daily the site returns 404 for me.

**Pull request merged**
