### PR TITLE
Feature: Support filtering custom emoji in reaction view

### PR DESCRIPTION
**Pull request by btylerh7**
I'm still relatively new to Android development, so please feel free to offer suggestions! I added a search input on top of the custom emoji view only when reacting. If the emoji category does not have any emoji in it, it will be hidden.

Screenshot 2023-09-23 at 11 33 47 AM
Screenshot 2023-09-23 at 11 34 10 AM

### CODE REVIEW

**Comment by btylerh7** [comment]
Of course I notice a bug right after I  submit this. If you go back to the timeline with the emoji picker open, it does not reset the list. So the next time you open the reaction selector on a post, it will show the previous filtered list. I'm guessing something needs to be reset when the keyboard closes, but I'm still new to a lot of this, so I am not sure where that code would need to be added.

**Comment by LucasGGamerM** [comment]
Having 2 input boxes is really confusing for new people. It is better to unify the boxes into a single one.

**Comment by btylerh7** [comment]
I agree. What do you think would be the best way to combine the inputs?

**Comment by btylerh7** [comment]
My first thought would be to check against the emoji regex, then if it matches an emoji react with that, but if it doesn't, start the search query

**Comment by LucasGGamerM** [comment]
We can change the position of the box later. And regex is a good way of doing it

**Comment by btylerh7** [comment]
New commit has the fields combined. This is what it looks like now: 
Emoji Keyboard with only one input text

It will only match the regex if the field was empty before (we don't need to run the check every time in this case) and then continues to filter if there was no emoji typed. Thoughts?

**Comment by sk22** [comment]
i actually tried implementing this myself when adding the emoji reaction support, but i failed - great to see you did it!! will definitely merge this soon, thanks!

**Pull request merged**
